# Здесь впиши свой токен бота (внутри кавычек)
bot_token: ""

# Здесь впиши чат id человека кому будут приходить анкеты на рассмотрения (без кавычек)
admin_group_chat_id:

# Здесь впиши id групп в которых ты добавил бота и в которые будет происходить рассылка от бота (после тире, без кавычек)
group_chatid:
  -